### ISSUE TITLE
Calluna-Exljbris 字体对数字显示非常差

### ISSUE THREAD

**Issue by wanglihe** [LinuxTOY/linuxtoy.org#1]
数字1看起来和字母I几乎一样，请更换主力字体。

**Comment by xuxiaodong** [comment]
其实我还蛮喜欢这款字体的，既然影响到了大家辨识，还是换了吧。目前已经换成 Noto 了，看看是否还满意？

**Comment by wanglihe** [comment]
主要是15和I5真的是很练眼力啊。换完之后有眼瞎复明的感觉，甚好。
