### ISSUE TITLE
现在github与主站的更新不同步？

### ISSUE THREAD

**Issue by wanglihe** [LinuxTOY/linuxtoy.org#3]
感觉主站好多天不更新，但是会突然一天更好多。
问题有可能是主站没有及时更新，或是更新了但是没更新文件时间造成浏览器不更新缓存，也有可能是纯我这边的问题，所以想问问目前主站的更新策略。

**Comment by xuxiaodong** [comment]
只要这里更新就会自动触发服务器上 Pelican 生成新页面，即一般来说主站在几分钟之后就会有新内容，试试刷新浏览器缓存。

**Comment by wanglihe** [comment]
确实是我电脑的firefox缓存而不主动刷新。我现在有点感兴趣这么弱鸡的问题为什么会在firefox里存在，而且我居然只在linuxtoy上，而且是改版pelican后，注意到这个问题。缓存无处不在，http里也有时间头，为什么就会发生呢？我自己再查查资料，但是这确实不是linuxtoy和pelican的问题。issue可以关了。
